const list = [
    {
      id: 1,
      title: "Purchase Items full of accessories.",
      author: "★★★☆☆",
      price: 89,
      img: "https://images.pexels.com/photos/631212/pexels-photo-631212.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      amount: 1,
    },
    {
      id: 2,
      title: "HD digital camera Pro with huge storage",
      author: "★★★★☆",
      price: 98,
      img: "https://images.pexels.com/photos/346817/pexels-photo-346817.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      amount: 1,
    },
    {
      id: 3,
      title: "Amazing high speed laptop 2023 edition",
      author: "★★★★☆",
      price: 143,
      img: "https://images.pexels.com/photos/4087468/pexels-photo-4087468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      amount: 1,
    },
    {
      id: 4,
      title: "Good quality clothes made with fibers and wollen",
      author: "★★★★☆",
      price: 57,
      img: "https://images.pexels.com/photos/8311884/pexels-photo-8311884.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      amount: 1,
    },
    {
      id: 5,
      title: "My First 1000 Words Book for children",
      author: "★★★★☆",
      price: 149,
      img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "High quality keyboard with autheticity",
      author: "★★★★☆",
      price: 135,
      img: "https://images.pexels.com/photos/7285478/pexels-photo-7285478.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      amount: 1,
    },
    {
      id: 7,
      title: "Plastic water bottles for more durability",
      author: "★★★★☆",
      price: 693,
      img: "https://images.pexels.com/photos/9736723/pexels-photo-9736723.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      amount: 1,
    },
    {
      id: 8,
      title: "Early Learning Library Pack (For childrens under 10)",
      author: "★★★★☆",
      price: 289,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Blossom Moral Story Book for Kids ",
      author: "★★★★☆",
      price: 80,
      img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Brain Activity Book for Kids (For childrens under 10)",
      author: "★★★★☆",
      price: 86,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Willy the Silly Panda  (For childrens under 10)",
      author: "★★★★☆",
      price: 120,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Grandma's Bag of Stories  (For childrens under 10)",
      author: "★★★★☆",
      price: 157,
      img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
];

export default list;